### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by milenkowski** [andrivet/python-asn1#49]
Hello, 

I am using your library to parse Windows catalog files (.cat). For some (not all) catalog files, I am getting the "IndexError: list index out of range" error when using your script dump.py (see Traceback). The error occurs only when some "tag, value" pairs are read (i.e., it may occur in the middle of file content dumping).

Do you have any solution to this issue?

Thank you.

------------

Traceback (most recent call last):
  File "dump.py", line 171, in <module>
    pretty_print(decoder, output_file)
  File "dump.py", line 143, in pretty_print
    pretty_print(input_stream, output_stream, indent + 2)
  File "dump.py", line 143, in pretty_print
    pretty_print(input_stream, output_stream, indent + 2)
  File "dump.py", line 143, in pretty_print
    pretty_print(input_stream, output_stream, indent + 2)
  [Previous line repeated 8 more times]
  File "dump.py", line 136, in pretty_print
    tag, value = input_stream.read()
  File "C:\Users\aleks\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\asn1.py", line 421, in read
    value = self._read_value(tag.nr, length)
  File "C:\Users\aleks\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\asn1.py", line 512, in _read_value
    value = self._decode_integer(bytes_data)
  File "C:\Users\aleks\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\asn1.py", line 567, in _decode_integer
    negative = values[0] & 0x80
IndexError: list index out of range

**Comment by andrivet** [comment]
No data provided, so no possible to reproduce.
